/**
 * transactions.js — seed data for pledges/transactions
 * 10 transactions spread across creators, campaigns, supporters, and payment methods.
 * All mock payments have status 'completed'.
 */

export const TRANSACTIONS = [
  // ── Tendai — Mwana WaMambo campaign ─────────────────────────────────────
  {
    id: 'txn-1',
    supporterId: 'user-supporter-1',
    creatorId: 'user-creator-1',
    campaignId: 'campaign-1',
    amount: 25,
    currency: 'USD',
    paymentMethod: 'ecocash',
    status: 'completed',
    supporterName: 'Chipo Ndlovu',
    createdAt: '2024-11-15T10:00:00.000Z',
  },
  {
    id: 'txn-2',
    supporterId: 'user-supporter-2',
    creatorId: 'user-creator-1',
    campaignId: 'campaign-1',
    amount: 50,
    currency: 'USD',
    paymentMethod: 'card',
    status: 'completed',
    supporterName: 'Farai Mutasa',
    createdAt: '2024-11-20T14:00:00.000Z',
  },
  {
    id: 'txn-3',
    supporterId: null,
    creatorId: 'user-creator-1',
    campaignId: 'campaign-1',
    amount: 100,
    currency: 'USD',
    paymentMethod: 'bank_transfer',
    status: 'completed',
    supporterName: 'Anonymous',
    createdAt: '2024-12-01T09:30:00.000Z',
  },
  {
    id: 'txn-4',
    supporterId: 'user-supporter-1',
    creatorId: 'user-creator-1',
    campaignId: 'campaign-1',
    amount: 30,
    currency: 'USD',
    paymentMethod: 'ecocash',
    status: 'completed',
    supporterName: 'Chipo Ndlovu',
    createdAt: '2024-12-10T11:00:00.000Z',
  },
  {
    id: 'txn-5',
    supporterId: 'user-supporter-2',
    creatorId: 'user-creator-1',
    campaignId: 'campaign-1',
    amount: 75,
    currency: 'USD',
    paymentMethod: 'card',
    status: 'completed',
    supporterName: 'Farai Mutasa',
    createdAt: '2025-01-02T16:00:00.000Z',
  },

  // ── Tendai — Mbare Mural (completed campaign) ───────────────────────────
  {
    id: 'txn-6',
    supporterId: 'user-supporter-1',
    creatorId: 'user-creator-1',
    campaignId: 'campaign-2',
    amount: 50,
    currency: 'USD',
    paymentMethod: 'ecocash',
    status: 'completed',
    supporterName: 'Chipo Ndlovu',
    createdAt: '2024-07-15T09:00:00.000Z',
  },
  {
    id: 'txn-7',
    supporterId: 'user-supporter-2',
    creatorId: 'user-creator-1',
    campaignId: 'campaign-2',
    amount: 100,
    currency: 'USD',
    paymentMethod: 'card',
    status: 'completed',
    supporterName: 'Farai Mutasa',
    createdAt: '2024-07-20T14:00:00.000Z',
  },

  // ── Rudo — Chimurenga Soul album campaign ───────────────────────────────
  {
    id: 'txn-8',
    supporterId: 'user-supporter-1',
    creatorId: 'user-creator-2',
    campaignId: 'campaign-3',
    amount: 20,
    currency: 'USD',
    paymentMethod: 'ecocash',
    status: 'completed',
    supporterName: 'Chipo Ndlovu',
    createdAt: '2024-12-05T10:00:00.000Z',
  },
  {
    id: 'txn-9',
    supporterId: 'user-supporter-2',
    creatorId: 'user-creator-2',
    campaignId: 'campaign-3',
    amount: 50,
    currency: 'USD',
    paymentMethod: 'card',
    status: 'completed',
    supporterName: 'Farai Mutasa',
    createdAt: '2024-12-15T15:00:00.000Z',
  },
  {
    id: 'txn-10',
    supporterId: null,
    creatorId: 'user-creator-2',
    campaignId: 'campaign-3',
    amount: 30,
    currency: 'USD',
    paymentMethod: 'ecocash',
    status: 'completed',
    supporterName: 'Anonymous',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
];
